version: '3.8'

services:
    UpAndRunning:
        image: kooldev/php:8.1
        container_name: UpAndRunning
        working_dir: /UpAndRunning
        restart: always
        networks:
            - internal
            - nginx_network
        volumes:
            - '.:/UpAndRunning'
            - './docker/php/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
        links:
            - UpAndRunning-database
        depends_on:
            - UpAndRunning-database
    UpAndRunning-nginx:
        image: nginx:alpine
        container_name: UpAndRunning-nginx
        restart: always
        working_dir: /UpAndRunning
        networks:
            - internal
            - nginx_network
        ports:
            - "9002:80"
        volumes:
            - .:/UpAndRunning
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - UpAndRunning
    UpAndRunning-composer:
        image: composer:latest
        container_name: UpAndRunning-composer
        working_dir: /UpAndRunning
        command: update --ignore-platform-reqs
        volumes:
            - .:/UpAndRunning
        restart: on-failure
        depends_on:
            - UpAndRunning
    UpAndRunning-database:
        image: mariadb:latest
        restart: always
        container_name: UpAndRunning-database
        working_dir: /UpAndRunning
        networks:
            - internal
            - nginx_network
        command: mysqld --skip-grant-tables
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=UpAndRunning
            - MYSQL_USER=root
            - MYSQL_PASSWORD=password
        volumes:
            - .:/UpAndRunning
            - ./UpAndRunning-database:/var/lib/mysql
        ports:
            - '8000:3306'
    UpAndRunning-redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - UpAndRunning-redis:/data
        networks:
            - internal
            - nginx_network
        command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

networks:
    nginx_network:
        external: true
    internal:
        driver: overlay
        name: 'global'
        attachable: true
volumes:
    UpAndRunning-database:
        driver: local
    UpAndRunning-redis:
        driver: local
